#include "bullet_binds.h"

namespace solstice {
    void SetupBulletBinds(kaguya::State& state) {
        state["BulletBase"].setClass(kaguya::UserdataMetatable<BulletBase, Particle>()
                         .addProperty("mShot", &BulletBase::mShot)
                         .addProperty("mAlive", &BulletBase::mAlive)
                         .addProperty("mTransfersVelocity", &BulletBase::mTransfersVelocity)
                         .addProperty("mTransfersPosition", &BulletBase::mTransfersPosition)
                         .addProperty("mEmitsOnImpact", &BulletBase::mEmitsOnImpact)
                         .addProperty("mMaxBounces", &BulletBase::mMaxBounces)
                         .addProperty("mBounces", &BulletBase::mBounces)
                         .addProperty("mElasticityX", &BulletBase::mElasticityX)
                         .addProperty("mElasticityY", &BulletBase::mElasticityY)
                         .addProperty("mHitBox", &BulletBase::mHitBox)
                         .addProperty("mEmitter", &BulletBase::mEmitter)
                         .addProperty("mImpactEmitter", &BulletBase::mImpactEmitter)
                         .addProperty("mImpactForce", &BulletBase::mImpactForce)
                         .addProperty("mBlastForce", &BulletBase::mBlastForce)
                         .addProperty("mRotatesSprite", &BulletBase::mRotatesSprite)
                         .addProperty("mType", &BulletBase::mType)
                         .addProperty("mSpriteAngle", &BulletBase::mSpriteAngle)
                         .addProperty("mAutoDeathDur", &BulletBase::mAutoDeathDur)
                         .addFunction("GetHitBoxPos", &BulletBase::GetHitBoxPos)
                         .addFunction("UpdateAnimation", &BulletBase::UpdateAnimation)
                         .addFunction("ShootAngle", &BulletBase::ShootAngle)
                         .addFunction("GetEmitter", &BulletBase::GetEmitterPtr)
                         .addFunction("SetEmitter", &BulletBase::SetEmitter)
                         .addFunction("GetImpactEmitter", &BulletBase::GetImpactEmitterPtr)
                         .addFunction("SetImpactEmitter", &BulletBase::SetImpactEmitter)
                         );
        state["Bullet"].setClass(kaguya::UserdataMetatable<Bullet, BulletBase>()
                         .setConstructors<Bullet()>()
                         .addProperty("mLockOnRadius", &Bullet::mLockOnRadius)
                         .addProperty("mBlastRadius", &Bullet::mBlastRadius)
                         .addProperty("mCollisionFound", &Bullet::mCollisionFound)
                         .addProperty("mLocksOn", &Bullet::mLocksOn)
                         .addProperty("mTargetFound", &Bullet::mTargetFound)
                         .addProperty("mAdjustsAngle", &Bullet::mAdjustsAngle)
                         .addProperty("mLockOnVel", &Bullet::mLockOnVel)
                         .addProperty("mLockOnStartVel", &Bullet::mLockOnStartVel)
                         .addProperty("mLockOnDir", &Bullet::mLockOnDir)
                         .addProperty("mLockOnSpeed", &Bullet::mLockOnSpeed)
                         .addProperty("mLockOnAccel", &Bullet::mLockOnAccel)
                         .addProperty("mTrackingSpeed", &Bullet::mTrackingSpeed)
                         .addProperty("mWaterStops", &Bullet::mWaterStops)
                         .addProperty("mLockOnPoint", &Bullet::mLockOnPoint)
                         .addProperty("mBouncesTowards", &Bullet::mBouncesTowards)
                         .addProperty("mDirectsImpact", &Bullet::mDirectsImpact)
                         .addProperty("mCreatesSubBullets", &Bullet::mCreatesSubBullets)
                         .addProperty("mCreateSubState", &Bullet::mCreateSubState)
                         .addProperty("mActionDelay", &Bullet::mActionDelay)
                         .addProperty("mSubBulletDir", &Bullet::mSubBulletDir)
                         .addProperty("mSubCreateFrame", &Bullet::mSubCreateFrame)
                         .addProperty("mSubCreateFrameCur", &Bullet::mSubCreateFrameCur)
                         .addProperty("mSubsPerShot", &Bullet::mSubsPerShot)
                         .addProperty("mSubsToMake", &Bullet::mSubsToMake)
                         .addProperty("mSubPosition", &Bullet::mSubPosition)
                         .addProperty("mSubDirection", &Bullet::mSubDirection)
                         .addProperty("mSubsFollowTarget", &Bullet::mSubsFollowTarget)
                         .addProperty("mDamagesSelf", &Bullet::mDamagesSelf)
                         .addProperty("mKnockbacksSelf", &Bullet::mKnockbacksSelf)
                         .addFunction("DefaultUpdate", &Bullet::DefaultUpdate)
                         .addFunction("DefaultCollision", &Bullet::DefaultResolveCollision)
                         .addFunction("InitHitBox", &Bullet::InitHitBox)
                         .addFunction("AimTowards", &Bullet::AimTowards)
                         .addFunction("ApplyImpulse", &Bullet::ApplyImpulse)
                         .addFunction("ApplyImpulseX", &Bullet::ApplyImpulseX)
                         .addFunction("ApplyImpulseY", &Bullet::ApplyImpulseY)
                         .addFunction("ApplyForce", &Bullet::ApplyForce)
                         .addFunction("ApplyForceX", &Bullet::ApplyForceX)
                         .addFunction("ApplyForceY", &Bullet::ApplyForceY)
                         .addFunction("AddAnimation", &Bullet::AddAnimation)
                         .addFunction("SetAnimation", &Bullet::SetAnimation)
                         .addFunction("SetDestroyAnim", &Bullet::SetDestroyAnim)
                         .addFunction("GetSpriteAnim", &Bullet::GetSpriteAnimationPtr)
                         .addFunction("SetHoriFlip", &Bullet::SetHoriFlip)
                         .addFunction("SetVertFlip", &Bullet::SetVertFlip)
                         .addFunction("GetCollisionType", &Bullet::GetCollisionType)
                         .addFunction("SetCollisionType", &Bullet::SetCollisionType)
                         .addFunction("AddSubSpawnOffset", &Bullet::AddSubSpawnOffset)
                         .addOverloadedFunctions("Reset", static_cast<void (Bullet::*)(void)>(&Bullet::Reset))
                         .addOverloadedFunctions("SetPosition", static_cast<void (Bullet::*)(Vector2f)>(&Bullet::SetPosition))
                         .addOverloadedFunctions("Shoot", static_cast<void (Bullet::*)(Vector2f)>(&Bullet::Shoot),
                                                          static_cast<void (Bullet::*)(Vector2f, Vector2f)>(&Bullet::Shoot)
                                                 )
                         );
        state["BulletType"].setClass(kaguya::UserdataMetatable<BulletType>()
                                    .setConstructors<BulletType(), BulletType(Bullet, int, float, float, int),
                                                     BulletType(string, int, float, float), BulletType(string, int, float, float, int)>()
                                     .addFunction("Init", &BulletType::Init)
                                     .addFunction("SetFireRate", &BulletType::SetFireRate)
                                     .addFunction("GetFireRate", &BulletType::GetFireRate)
                                     .addFunction("SetMaxShots", &BulletType::SetMaxShots)
                                     .addFunction("GetMaxShots", &BulletType::GetMaxShots)
                                     .addFunction("SetShotsPerFrame", &BulletType::SetShotsPerFrame)
                                     .addFunction("GetShotsPerFrame", &BulletType::GetShotsPerFrame)
                                     .addFunction("SetName", &BulletType::SetName)
                                     .addFunction("GetName", &BulletType::GetName)
                                     .addFunction("SetBaseBullet", &BulletType::SetBaseBullet)
                                     .addFunction("GetBaseBullet", &BulletType::GetBaseBullet)
                                     .addFunction("GetShotForce", &BulletType::GetShotForce)
                                     .addFunction("GetFlashColor", &BulletType::GetFlashColor)
                                     .addFunction("SetMagicCost", &BulletType::SetMagicCost)
                                     .addFunction("GetMagicCost", &BulletType::GetMagicCost)
                                     .addFunction("DefaultCreateShot", &BulletType::DefaultCreateShot)
                                     .addFunction("GetBullet", &BulletType::GetBulletPtr)
                                     .addFunction("SetCurTime", &BulletType::SetCurTime)
                                     .addFunction("CanCreate", &BulletType::CanCreate)
                                     .addFunction("GetAngleStep", &BulletType::GetAngleStep)
                                     .addFunction("GetLastInactive", &BulletType::GetLastInactive)
                                     .addFunction("IncrementLastInactive", &BulletType::IncrementLastInactive)
                                     .addFunction("SetHoldShot", &BulletType::SetHoldShot)
                                     .addFunction("GetHoldShot", &BulletType::GetHoldShot)
                                     .addFunction("SetSubCreateDelay", &BulletType::SetSubCreateDelay)
                                     .addFunction("SetChargeable", &BulletType::SetChargeable)
                                     .addFunction("GetChargeable", &BulletType::GetChargeable)
                                     .addFunction("SetShootOnRelease", &BulletType::SetShootOnRelease)
                                     .addFunction("SetChargeForceStep", &BulletType::SetChargeForceStep)
                                     .addFunction("SetChargeForceStart", &BulletType::SetChargeForceStart)
                                     .addFunction("SetChargeDirection", &BulletType::SetChargeDirection)
                                     .addFunction("SetDelayTimer", &BulletType::SetDelayTimer)
                                     .addFunction("GetDelayTimerCur", &BulletType::GetDelayTimerCur)
                                     .addFunction("GetDelayTimer", &BulletType::GetDelayTimer)
                                     .addFunction("IncrementDelayTimer", &BulletType::IncrementDelayTimer)
                                     .addFunction("GetNextSpawnDir", &BulletType::GetNextSpawnDir)
                                     .addFunction("SetNextSpawnDir", &BulletType::SetNextSpawnDir)
                                     .addFunction("GetNextSpawnPos", &BulletType::GetNextSpawnPos)
                                     .addFunction("SetNextSpawnPos", &BulletType::SetNextSpawnPos)
                                     .addFunction("SetNextToMake", &BulletType::SetNextToMake)
                                     .addFunction("GetNextToMake", &BulletType::GetNextToMake)
                                     .addFunction("GetNextPerShot", &BulletType::GetNextPerShot)
                                     .addFunction("SetNextPerShot", &BulletType::SetNextPerShot)
                                     .addFunction("GetTargetPosition", &BulletType::GetTargetPosition)
                                     .addFunction("SetTargetPosition", &BulletType::SetTargetPosition)
                                     .addFunction("SetPackagNamee", &BulletType::SetPackageName)
                                     .addFunction("GetPackageName", &BulletType::GetPackageName)
                                     .addFunction("SetCreateFunc", &BulletType::SetCreateFuncStr)
                                     .addFunction("SetMultiShotAngleArc", &BulletType::SetMultiShotAngleArc)
                                     .addFunction("GetShotType", &BulletType::GetShotType)
                                     .addFunction("SetShotType", &BulletType::SetShotType)
                                     .addFunction("GetModType", &BulletType::GetModType)
                                     .addFunction("SetModType", &BulletType::SetModType)
                                     .addFunction("SetSubBulletID", &BulletType::SetSubBulletID)
                                     .addFunction("FindNextInactive", &BulletType::FindNextInactive)
                                     .addFunction("SetNextSpawnVel", &BulletType::SetNextSpawnVel)
                                     .addFunction("GetNextSpawnVel", &BulletType::GetNextSpawnVel)
                                     .addFunction("GetChargingShot", &BulletType::GetChargingShot)
                                     .addFunction("SetChargingShot", &BulletType::SetChargingShot)
                                     .addFunction("GetShotQueued", &BulletType::GetShotQueued)
                                     .addFunction("SetShotQueued", &BulletType::SetShotQueued)
                                     .addFunction("SetChargeStep", &BulletType::SetChargeStep)
                                     .addFunction("GetChargeStep", &BulletType::GetChargeStep)
                                     .addFunction("SetCharge", &BulletType::SetCharge)
                                     .addFunction("SetTypes", &BulletType::SetTypes)
                                     .addFunction("SetAutoReleaseCharge", &BulletType::SetAutoReleaseCharge)
                                     .addFunction("GetAutoReleaseCharge", &BulletType::GetAutoReleaseCharge)
                                     .addOverloadedFunctions("SetFlashColor", static_cast<void (BulletType::*)(Color)>(&BulletType::SetFlashColor),
                                                                            static_cast<void (BulletType::*)(float, float, float)>(&BulletType::SetFlashColor))
                                     );
    state["BTYPE_PROJECTILE"] = BTYPE_PROJECTILE;
    state["BTYPE_LASER"] = BTYPE_LASER;
    state["BTYPE_SUSTAINED"] = BTYPE_SUSTAINED;
    state["BTYPE_MELEE"] = BTYPE_MELEE;
    }
}

